from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float
import argparse


PATH_HELP = '''
  This is the file path to the database. If it's a relative path use:
  foo.db
  If it's an absolute path (quotation marks are required!) use:
  #Unix/Mac
  "/absolute/path/to/foo.db"
  #Windows
  "C:\\path\\to\\foo.db"
'''

DEBUG_HELP = '''
  Turns echo on so SQL statements generated by the script are printed to the terminal.
'''


_meta = MetaData()

# create database table
market_summaries = Table('marketsummaries', _meta,
  Column('MarketName', String(), primary_key=True),
  Column('High', Float()),
  Column('Low', Float()),
  Column('Volume', Float()),
  Column('Last', Float()),
  Column('BaseVolume', Float()),
  Column('TimeStamp', String()),
  Column('Bid', Float()),
  Column('Ask', Float()),
  Column('OpenBuyOrders', Integer()),
  Column('OpenSellOrders', Integer()),
  Column('PrevDay', Float()),
  Column('Created', String()),
)


def db_connect(conn_string, echo=False):
  # put create_engine, create_all, and connect under the same function for simplicity.
  engine = create_engine(conn_string, echo=echo)
  # we could put create_all somewhere else since we don't need to create the table for summary.py
  _meta.create_all(engine)
  return engine.connect()
